### ISSUE TITLE
Se corta el tooltip

### ISSUE THREAD

**Issue by McGiverGim** [danimart1991/pvpc-hourly-pricing-card#3]
Hola! Gracias por la card...
No sé si es por alguna de las custom card que uso, pero el tooltip con los datos se corta:

![image](https://user-images.githubusercontent.com/2673520/79307893-ec051780-7ef7-11ea-8d7b-210d54e84e82.png)

Aquí está las cards que uso:

```yaml
cards:
  - entities:
      - entities:
          - attribute: next_best_at
            name: Siguientes
        entity: sensor.pvpc_horario_dha
        name: Mínimo
        secondary_info:
          attribute: min_price_at
          name: A las
        show_state: false
        type: 'custom:multiple-entity-row'
    type: entities
  - type: 'custom:pvpc-hourly-pricing-card'
    title: PVPC por hora DHA
    entity_id: sensor.pvpc_horario_dha
title: Coste kWh
type: 'custom:stack-in-card'
```
